sudo: 'required'

services:
  - docker

before_install:
- docker build -t nurlan1992/hello-world:v1.0 .
- docker login -u $DOCKER_USER -p $DOCKER_PASS -e $DOCKER_EMAIL
- docker push nurlan1992/hello-world


script:
  - 'make test'
  - 'make image'
  
 after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make push-image ;
    fi

# don't notify me when things fail
notifications:
  email: false
